### ISSUE TITLE
Can this action support the `latest` version?

### ISSUE THREAD

**Issue by Dup4** [jwlawson/actions-setup-bazel#25]
```yaml
      - name: Setup bazel
        uses: jwlawson/actions-setup-bazel@v1
        with:
          bazel-version: "latest"
```

I used the action with the above configuration, but it gave me the error shown below.

<img width="489" alt="image" src="https://user-images.githubusercontent.com/38343778/209553942-ab388726-74bf-4caa-8a74-8356908aa1b6.png">

So, can you support `latest` version?

Just like the `actions-setup-cmake` action.

```yaml
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: "latest"
```

It can be used like this.
